#!/bin/sh

set -e

raspi-config nonint do_boot_wait 1 >/dev/null || true

if [ -d /run/systemd/system ]; then
    systemctl --system daemon-reload >/dev/null || true
fi

if deb-systemd-helper --quiet debian-installed dhcpcd.service \
  && deb-systemd-helper --quiet is-enabled dhcpcd.service; then
    deb-systemd-invoke restart dhcpcd.service >/dev/null || true
fi

#DEBHELPER#

exit 0
