#!/bin/sh

set -e

if [ -d /run/systemd/system ]; then
    systemctl --system daemon-reload >/dev/null || true
fi

if deb-systemd-helper --quiet debian-installed NetworkManager.service \
  && deb-systemd-helper --quiet is-enabled NetworkManager.service; then
    deb-systemd-invoke restart NetworkManager.service >/dev/null || true
fi

#DEBHELPER#

exit 0
